[package]
name = "lgeo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lmaths = "1.0.4"
smallvec = "1.6.1"